
name: Java Lint Check

on:
  push:
    branches:
      - main  # Run on pushes to the main branch (change to your default branch if different)
      - feature/*  # Run on pushes to feature branches
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  lint:
    runs-on: ubuntu-latest  # Set the runner to Ubuntu

    steps:
    # Step 1: Checkout the repository code
    - name: Check out the code
      uses: actions/checkout@v2

    # Step 2: Set up Java JDK (using Java 11 in this case)
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    # Step 3: Install Checkstyle (or any other linter you want)
    - name: Download Checkstyle
      run: |
        curl -L https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar -o checkstyle.jar

    # Step 4: Run Checkstyle on the Java source code
    - name: Run Checkstyle
      run: |
        java -jar checkstyle.jar -c /google_checks.xml src/**/*.java
        # You can replace "/google_checks.xml" with your own Checkstyle configuration file
        # Make sure to adjust the "src/**/*.java" path to your project structure
