
name: Java Lint Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  lint:
    runs-on: ubuntu-latestc
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: temurin   # Updated to use temurin
          architecture: x64

      - name: Download Checkstyle
        run: |
          curl -L https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar -o checkstyle.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c /google_checks.xml src/**/*.java
