name: Java Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Install Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar -O checkstyle.jar
          echo "Checkstyle downloaded"

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml src/**/*.java
        # This command runs Checkstyle with the Google Java style config on all Java files in the 'src' directory.
        # You can adjust the config URL or your directory structure as needed.

      - name: Show Checkstyle Results
        run: |
          if [ -f checkstyle-result.xml ]; then
            cat checkstyle-result.xml
          else
            echo "No Checkstyle issues found."
          fi
