name: Lint GitHub Actions Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run actionlint
        uses: rhysd/actionlint@v2
        with:
          github_token: ${{  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 }}  # Use the automatically provided GITHUB_TOKEN
