name: Lint GitHub Actions Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run actionlint
        uses: rhysd/actionlint@v1  # Use v1 if v2 is not available
        with:
          github_token: ${{ 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}}
